typos corrected and added some explanations
paradigmxyz/sinker pull request #8
Opened 2023-12-26 18:43 UTC by hkey0

Minor typos corrected and explanations added.

2023-12-31 01:13 UTC, loren requested changes

2023-12-31 01:13 UTC, loren commented on README.md
> +- A Student and a Teacher refers to a Person
this is correct as is

2023-12-31 01:13 UTC, loren commented on README.md
> +- Students have taken and belong to many Courses through the Enrollment join table
I'd prefer to keep this language as HABTM is a standard way to indicate a many-to-many relationship.

2023-12-31 01:13 UTC, loren commented on README.md
> +The changes into the materialized view are sent to a logical replication slot. Sinker reads from this slot and indexes the
I think "changes to" is correct as is.

2023-12-31 01:13 UTC, loren commented on README.md
> +Run tests (with -s option to allow more verbose output):
👍

2023-12-31 05:24 UTC, hkey0 commented
Thank you for your attention. I have made the requested corrections. Thanks again :)

2024-01-02 16:03 UTC, loren approved these changes
thank you for contributing!

2024-01-02 16:03 UTC, merged